### ISSUE TITLE
DMCA takedown of DayZ Garage mod?

### ISSUE THREAD

**Issue by RedFalconKen** [SirFrostingham/DayZ_SA_NoMoreSurvivorName#1]
Claiming that it contained some script from your included init.c (where there is no init.c file in the Garage mod PBO)?? Completely ridiculous...

**Comment by SirFrostingham** [comment]
Hi. Did you comment on the wrong repo? I am not sure what you mean. I have not issued a DMCA takedown to anyone. Have a good one.

**Comment by RedFalconKen** [comment]
This repo was referenced in a DMCA notice:
Code inside the pbo file of the uploaded content are a copy of my code.

DMCA Takedown Notice on your item
Valve has received a DMCA copyright take down notice directed at your workshop item for DayZ posting on Steam, at https://steamcommunity.com/sharedfiles/filedetails/?id=2275791754. A copy of the notice is set forth in full at the end of this email.
A***** R*** alleges that he is the owner of the copyright in https://github.com/SirFrostingham/DayZ_SA_NoMoreSurvivorName and that publication of the content without his authorization infringes his rights.
.......

MissionServer.c
init.c
ORIGINAL CONTENT
the original content url is: https://github.com/SirFrostingham/DayZ_SA_NoMoreSurvivorName

the code inside the file: "@NoMoreSurvivorName/Missions/dayzOffline.chernarusplus/init.c"
has been repacked/stolen.

i did not authorise that.
Plaintiff
A**** R****

**Comment by RedFalconKen** [comment]
I guess someone is using your name/repo in filing a DMCA... sorry for the bother.

**Comment by SirFrostingham** [comment]
Wow. Yeah. It’s most definitely not me. They are using my info though. That’s stupid. Please disregard.
